### ISSUE TITLE
Error libthcli.so: cannot open shared object file: No such file or directory in Docker

### ISSUE THREAD

**Issue by jjschwarz** [OpenInformix/node-informixdb#14]
I am building a docker image which include informixdb 2.1.0, so based on 
https://github.com/OpenInformix/node-informixdb/blob/master/INSTALL.md

I included informixdb and moment in my Dockerfile dependencies.  It appears to pass all of the installation fine, but when I run my code I get the error:

(node:9) UnhandledPromiseRejectionWarning: Error: libthcli.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/src/app/node_modules/informixdb/lib/odbc.js:35:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
(node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The libthcli.so file appears to be installed at /usr/src/app/node_modules/informixdb/installer/onedb-odbc-driver/lib/cli/ .  I have tried adding a ld.so.conf line to look at that path, but it did not change the behavior.  

Any suggestions on how to fix this issue?

**Comment by jjschwarz** [comment]
Found the issue was my environment variables were not exposed fully when node ran.  Fixed now.

**Comment by melmac-dev** [comment]
> Found the issue was my environment variables were not exposed fully when node ran. Fixed now.

Could you please describe which variables you have exposed. Now I have the same problem.

**Comment by welsh11** [comment]
> Found the issue was my environment variables were not exposed fully when node ran. Fixed now.

@jjschwarz I would be really interested in knowing how you fixed this as I have the same issue.  Could you possibly share your solution please?
Thanks!

**Comment by jjschwarz** [comment]
Sorry, was out of the office, but I ended up doing this in my Dockerfile:
ENV INFORMIXDIR=/usr/src/app/node_modules/informixdb/installer/onedb-odbc-driver
ENV LD_LIBRARY_PATH=${INFORMIXDIR}/lib:${INFORMIXDIR}/lib/esql:${INFORMIXDIR}/lib/cli
ENV DB_LOCALE=en_US.57372

That seemed to resolve the issue

**Comment by welsh11** [comment]
@jjschwarz Very much appreciated!
